version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wlm-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true